In [24]:
import pandas as pd

data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]

df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [25]:
data = [["yash",34],["Alice",27],["Abhi",32],["Sonu",22],["Ankur",31]]

In [26]:
data

[['yash', 34], ['Alice', 27], ['Abhi', 32], ['Sonu', 22], ['Ankur', 31]]

In [27]:
pd.DataFrame(data,columns=["Name","Marks"])

    Name  Marks
0   yash     34
1  Alice     27
2   Abhi     32
3   Sonu     22
4  Ankur     31

In [28]:
data1 = {"a":[1,2,3], "b":[4,5,6],"c":[7,8,9]}

In [29]:
data1

{'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]}

In [30]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr, columns=["A", "B"])

In [31]:
df

   A  B
0  1  2
1  3  4

In [38]:
pd.read_csv ("data.csv")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2